import Head from "next/head";
// import Image from 'next/image'
// import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'
import { useEffect, useState } from "react";
import { supabase } from "./../../src/pages/api/supabaseCient";
import Auth from "../../components/Auth";
import UserArea from "../../components/UserArea";

export default function Home() {
  const [session, setSession] = useState("");

  useEffect(() => {
    setSession(supabase.auth.getUser());

    supabase.auth.onAuthStateChange((event, session) => {
      console.log(event, session);
      setSession(session);
    });
  }, []);

  return (
    <div /*className={styles.container}*/>
      <Head>
        <title>IziQ-Study</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {session != null ? <UserArea /> : <Auth />}
      {/* <Auth /> */}
    </div>
  );
}
